GameCatalogMVC/Controllers/HomeController.cs
using System;
using System.Web.Mvc;
using GameCatalogMVC.Models;
using System.Web.Helpers;
using System.Configuration;
using Microsoft.Web.Helpers;

namespace GameCatalogMVC.Controllers
{
    public class HomeController : Controller
    {       
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Localizacao()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Contato()
        {
            return View();
        }

        [HttpPost]        
        //public ActionResult Email_Enviar(string nomeremetente, string emailremetente, string body)
        public ActionResult Contato(Email Model)
        {
            if (!ReCaptcha.Validate(System.Configuration.ConfigurationManager.AppSettings["ReCaptchaPrivateKey"]))
            {
                ViewData.ModelState.AddModelError("_FORM", "Digite o código de verificação corretamente");
                return View();
            }

            if (ModelState.IsValid)
            {
                try
                {
                     WebMail.SmtpServer = ConfigurationManager.AppSettings["email_smtpserver"];              
                    WebMail.SmtpPort = Int32.Parse(ConfigurationManager.AppSettings["email_smtpport"]);                    
                    WebMail.EnableSsl = bool.Parse(ConfigurationManager.AppSettings["email_enablessl"]);
                    WebMail.UserName = ConfigurationManager.AppSettings["email_username"];                  
                    WebMail.Password = ConfigurationManager.AppSettings["email_password"];                    
                    string emailaddress = ConfigurationManager.AppSettings["email_address"];
                    WebMail.From = Model.EmailRemetente;
                    string NomeRemetente = Server.HtmlEncode(Model.NomeRemetente);
                    string Mensagem = Server.HtmlEncode(Model.Mensagem);
                    string Body = "Enviado por: <b>" + NomeRemetente + " (" + Model.EmailRemetente + ")</b><br /><br />" + Mensagem;
                    WebMail.Send(to: emailaddress, subject: "Contato de visitante no site em " + DateTime.Today.ToShortDateString(), body: Body, replyTo: Model.EmailRemetente);                    
                    ViewBag.Enviado = 1;
                    return View();
                }
                catch (Exception ex)
                {
                    ViewData.ModelState.AddModelError("_FORM", "Ocorreu um erro no envio do e-mail.");
                    //ViewData.ModelState.AddModelError("_FORM", ex.ToString());
                    ViewBag.Enviado = 0;
                    return View();
                }
            }
            else
            {
                return View();
            }
        }
        
    }
}

GameCatalogMVC/Controllers/ProdutoController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using GameCatalogMVC.DAL;

namespace GameCatalogMVC.Controllers
{
    public class ProdutoController : Controller
    {
        private IProdutoRepository produtoRepository;

        public ProdutoController()
        {
            this.produtoRepository = new ProdutoRepository(new GamecatalogmvcContext());
        }

        public ProdutoController(IProdutoRepository produtoRepository)
        {
            this.produtoRepository = produtoRepository;
        }

        public PartialViewResult DataList()
        {            
            var model = produtoRepository.GetLancamentos();
            return PartialView("DataList", model);
        }
        
        public ActionResult BuscabyTipoConsole(byte tipo, byte console, string mensagem)
        {
            // busca por tipo (1-console, 2-game, 3-acessório) 
            // busca por console (1-Playstation 3, 2-Playstation 2, 3-PSP, 4-xbox 360, 5-PC, 6-DS, 7-Wii)
            // Exibe somente os produtos com o campo exibir=1
            // ordena por data de cadastro desc                                    
            var modelBusca = produtoRepository.GetbyTipoConsole(tipo, console);

            ViewBag.NProdutos = modelBusca.Count();
            ViewBag.Tipo = tipo;
            ViewBag.Console = console;
            ViewBag.Descricao = "0";
            ViewBag.Categoria = 0;
            ViewBag.Ordem = 2;              //DataLancamentoDESC            
            ViewBag.Mensagem = mensagem;    //  mensagem na hora da busca dizendo se é jogo, acessório ou console
            
            return View("ResultBusca", modelBusca);
        }

        // armazena em cache a descrição de todos os jogos
        // a duração do cache é em segundos
        // portanto para deixar 1 dia em cache: 60 seconds * 60 minutes * 24 hours = 86400
        [OutputCache(Duration = 86400, VaryByParam = "none")]
        public JsonResult RetornaNomeProdutos()
        {            
            var modelBusca = produtoRepository.RetornaNomeProdutos();

            return Json(modelBusca);
        }
        
        public ActionResult BuscabyDescricao(string descricao)
        {
            if (String.IsNullOrWhiteSpace(descricao))
                return View("ResultBusca_Error");

            // busca por descrição do produto
            // ordena por data de cadastro desc            
            var modelBusca = produtoRepository.GetbyDescricao(descricao);

            ViewBag.NProdutos = modelBusca.Count();
            ViewBag.Tipo = 0;
            ViewBag.Console = 0;
            ViewBag.Descricao = descricao;
            ViewBag.Categoria = 0;
            ViewBag.Ordem = 2;        //DataLancamentoDESC  
            ViewBag.EhPesquisa = true;
            return View("ResultBusca", modelBusca);
        }

        public PartialViewResult BuscabyTipoConsoleDescricaoCategoriaOrdem(byte tipo, byte console, string descricao, byte categoria, int ordem)
        {
            // Exibe somente os produtos com o campo exibir=1
            // ordena por data de cadastro desc                        
            var modelBuscaOrd = produtoRepository.GetbyTipoConsoleDescricaoCategoriaOrdem(tipo, console, descricao, categoria, ordem );

            ViewBag.NProdutos = modelBuscaOrd.Count();
            ViewBag.Tipo = tipo;
            ViewBag.Console = console;            
            ViewBag.Descricao = descricao;
            ViewBag.Categoria = categoria;
            ViewBag.Ordem = ordem;
            
            return PartialView("ResultBusca_Detalhes", modelBuscaOrd);
        }


        public ActionResult Details(int idproduto)
        {
            var model = produtoRepository.GetbyID(idproduto);
            return View(model);
        }


    }
}

GameCatalogMVC/Views/Home/Carousel.cshtml
@{    
    Layout = null;          //instrução para não herdar da página de layout
}

<!DOCTYPE HTML>
<html lang="pt-br">
<body>       
    <div class="container-fluid">
        <div style="margin-top:1%">            
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-4 col-sm-offset-4 col-xs-0 col-xs-offset-12">
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                            <li data-target="#myCarousel" data-slide-to="2"></li>
                            <li data-target="#myCarousel" data-slide-to="3"></li>
                            <li data-target="#myCarousel" data-slide-to="4"></li>
                            <li data-target="#myCarousel" data-slide-to="5"></li>
                            <li data-target="#myCarousel" data-slide-to="6"></li>
                            <li data-target="#myCarousel" data-slide-to="7"></li>
                            <li data-target="#myCarousel" data-slide-to="8"></li>
                            <li data-target="#myCarousel" data-slide-to="9"></li>
                            <li data-target="#myCarousel" data-slide-to="10"></li>
                            <li data-target="#myCarousel" data-slide-to="11"></li>
                            <li data-target="#myCarousel" data-slide-to="12"></li>
                            <li data-target="#myCarousel" data-slide-to="13"></li>
                            <li data-target="#myCarousel" data-slide-to="14"></li>
                            <li data-target="#myCarousel" data-slide-to="15"></li>
                            <li data-target="#myCarousel" data-slide-to="16"></li>
                            <li data-target="#myCarousel" data-slide-to="17"></li>
                            <li data-target="#myCarousel" data-slide-to="18"></li>
                            <li data-target="#myCarousel" data-slide-to="19"></li>
                            <li data-target="#myCarousel" data-slide-to="20"></li>
                            <li data-target="#myCarousel" data-slide-to="21"></li>
                            <li data-target="#myCarousel" data-slide-to="22"></li>
                            <li data-target="#myCarousel" data-slide-to="23"></li>
                            <li data-target="#myCarousel" data-slide-to="24"></li>
                            <li data-target="#myCarousel" data-slide-to="25"></li>
                            <li data-target="#myCarousel" data-slide-to="26"></li>
                            <li data-target="#myCarousel" data-slide-to="27"></li>
                            <li data-target="#myCarousel" data-slide-to="28"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="~/Content/carousel/slides/slide1.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide2.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide3.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide4.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide5.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide6.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide7.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide8.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide9.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide10.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide11.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide12.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide13.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide14.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide15.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide16.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide17.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide18.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide19.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide20.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide21.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide22.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide23.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide24.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide25.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide26.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide27.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide28.jpg">
                            </div>
                            <div class="item">
                                <img src="~/Content/carousel/slides/slide29.jpg">
                            </div>

                            <!-- Left and right controls -->
                            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</body>
</html>

GameCatalogMVC/Views/Home/Contato.cshtml
@model GameCatalogMVC.Models.Email
           
@{ 
    ViewBag.Title = "Contato_Enviar";    
}

@section Styles
{
    <style type="text/css">
        #divcontato {
            font-family: Verdana;
            font-size:small;
            background-color: White;
            height: 450px;
        }
        #txtNomeRemetente, #txtEmailRemetente
        {
            width: 350px;
        }
        #txtMensagem
        {
            width: 400px;
            height: 100px;
        }
        #divRecaptcha
        {
            margin-left:50px;
        }
        #btnEnviar
        {
            margin-left:150px;
        }   
        .modal {
          text-align: center;
          padding: 0!important;
          vertical-align: middle;
        }
    </style>    
}

@section Scripts
{
    <script>
          $(document).ready(function(){                            
              $('#divModal').modal()
          });
    </script>
}


<div id="divcontato" class="container-fluid col-lg-12 col-md-12 col-sm-12 col-xs-12">    
    <div>
        <br />
        <strong>Entre em contato com a Game Catalog MVC</strong>
        <br />
        <br />
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(false, "Atenção:");
            <table>
                <tr>
                    <td>Nome:</td>
                    <td>
                        @Html.TextBoxFor(m => m.NomeRemetente, new { id = "txtNomeRemetente", maxlength = 50 })
                        @Html.ValidationMessageFor(m => m.NomeRemetente, "*")
                    </td>
                </tr>
                <tr>
                    <td>E-mail:</td>
                    <td>
                        @Html.TextBoxFor(m => m.EmailRemetente, new { id = "txtEmailRemetente", maxlength = 50 })
                        @Html.ValidationMessageFor(m => m.EmailRemetente, "*")
                    </td>
                </tr>
                <tr>
                    <td valign="top">Mensagem:</td>
                    <td>
                        @Html.TextAreaFor(m => m.Mensagem, new { id = "txtMensagem", maxlength = 4000 })
                        @Html.ValidationMessageFor(m => m.Mensagem, "*")
                    </td>
                </tr>
            </table>
            <br />
            <div id="divRecaptcha">
                @ReCaptcha.GetHtml(language: "pt-br", theme: "white")
            </div>
            <br />
            <button id="btnEnviar" class="btn-info btn-lg" alt="Enviar" title="Enviar e-mail"><span class="glyphicon glyphicon-envelope">&nbsp;Enviar</span></button>            
        }                    
        @if (@ViewBag.Enviado == 1)
        {
            <div id="divModal" class="modal fade" tabindex="-1">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Sucesso</h4>
                        </div>
                        <div class="modal-body">                            
                            <h2>Email enviado!</h2>
                            <span>Obrigado por entrar em contato com a Game Catalog MVC</span>
                            <br />
                            <span>Sua mensagem será respondida em breve.</span>
                        </div>
                        <div class="modal-footer">                            
                            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                        </div>
                    </div>
                </div>
            </div>
            }        
        <br />
        <br />
        <hr />  
    </div>    
</div>

GameCatalogMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@Html.Partial("Carousel")
@Html.Action("DataList", "Produto")

GameCatalogMVC/Views/Home/Localizacao.cshtml
@{
    ViewBag.Title = "Localizacao";
}

@section Styles
{
    <style type="text/css">
        #divLocalizacaoTexto
        {
            font-size: small;
            background-color: White;   
            font-family:Verdana;                                                                  
        }    
    </style>    
}

<div class="container-fluid  col-lg-12 col-md-12 col-sm-12 col-xs-12">    
        <div id="divLocalizacaoTexto" class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <strong>Game Catalog MVC</strong>
            <br />
            Piazza del Colosseo, 1<br />
            CEP: 00184
            <br />
            Roma - Italia
            <br />
            Fone: (11) 2980-43XX               
            <br />
            <br />
            <br />
        </div>
        <div id="divLocalizacaoMapa" class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
            <iframe width="618" height="509" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2970.123073808986!2d12.490042215441486!3d41.89021017922119!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132f61b6532013ad%3A0x28f1c82e908503c4!2sColosseum!5e0!3m2!1spt-BR!2sus!4v1482266024123" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
</div>