GameCatalogMVC/Models/Produto.cs
using System;
using System.Data.SqlClient;
using System.Configuration;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace GameCatalogMVC.Models
{
    [Table("Produto")]
    public class Produto
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdProduto { get; set; }
        [MaxLength(60, ErrorMessage = "Máximo 60 caracteres")]
        public string Descricao { get; set; }
        public byte? IdCategoria { get; set; }
        public byte? IdConsole { get; set; }
        public byte? IdTipo { get; set; }
        [MaxLength(40)]
        public string Texto1 { get; set; }
        [MaxLength(40)]
        public string Texto2 { get; set; }
        [MaxLength(40)]
        public string Texto3 { get; set; }
        [MaxLength(60)]
        public string Foto { get; set; }
        [MaxLength(80)]
        public string Site { get; set; }
        public byte? Exibir_na_pag_principal { get; set; }
        public byte? Ativo { get; set; }
        public DateTime Data_cadastro { get; set; }

        [ForeignKey("IdTipo")]
        public virtual Tipo Tipo { get; set; }
        [ForeignKey("IdConsole")]
        public virtual Console Console { get; set; }
        [ForeignKey("IdCategoria")]
        public virtual Categoria Categoria { get; set; }
    }
}

GameCatalogMVC/Controllers/CategoriaController.cs
using System.Web.Mvc;
using GameCatalogMVC.DAL;

namespace GameCatalogMVC.Controllers
{
    public class CategoriaController : Controller
    {
        private ICategoriaRepository categoriaRepository;

        public CategoriaController()
        {
            this.categoriaRepository = new CategoriaRepository(new GamecatalogmvcContext());
        }

        public CategoriaController(ICategoriaRepository categoriaRepository)
        {
            this.categoriaRepository = categoriaRepository;
        }
        public PartialViewResult ListaCategorias(int tipo, int console,  int ordem)
        {            
            var model = categoriaRepository.GetCategorias();
            ViewBag.Tipo = tipo;
            ViewBag.Console = console;                        
            ViewBag.Ordem = ordem;            
            return PartialView(model);
        }

    }
}

GameCatalogMVC/Controllers/ProdutoController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using GameCatalogMVC.DAL;

namespace GameCatalogMVC.Controllers
{
    public class ProdutoController : Controller
    {
        private IProdutoRepository produtoRepository;

        public ProdutoController()
        {
            this.produtoRepository = new ProdutoRepository(new GamecatalogmvcContext());
        }

        public ProdutoController(IProdutoRepository produtoRepository)
        {
            this.produtoRepository = produtoRepository;
        }

        public PartialViewResult DataList()
        {            
            var model = produtoRepository.GetLancamentos();
            return PartialView("DataList", model);
        }
        
        public ActionResult BuscabyTipoConsole(byte tipo, byte console, string mensagem)
        {
            // busca por tipo (1-console, 2-game, 3-acessório) 
            // busca por console (1-Playstation 3, 2-Playstation 2, 3-PSP, 4-xbox 360, 5-PC, 6-DS, 7-Wii)
            // Exibe somente os produtos com o campo exibir=1
            // ordena por data de cadastro desc                                    
            var modelBusca = produtoRepository.GetbyTipoConsole(tipo, console);

            ViewBag.NProdutos = modelBusca.Count();
            ViewBag.Tipo = tipo;
            ViewBag.Console = console;
            ViewBag.Descricao = "0";
            ViewBag.Categoria = 0;
            ViewBag.Ordem = 2;              //DataLancamentoDESC            
            ViewBag.Mensagem = mensagem;    //  mensagem na hora da busca dizendo se é jogo, acessório ou console
            
            return View("ResultBusca", modelBusca);
        }

        // armazena em cache a descrição de todos os jogos
        // a duração do cache é em segundos
        // portanto para deixar 1 dia em cache: 60 seconds * 60 minutes * 24 hours = 86400
        [OutputCache(Duration = 86400, VaryByParam = "none")]
        public JsonResult RetornaNomeProdutos()
        {            
            var modelBusca = produtoRepository.RetornaNomeProdutos();

            return Json(modelBusca);
        }
        
        public ActionResult BuscabyDescricao(string descricao)
        {
            if (String.IsNullOrWhiteSpace(descricao))
                return View("ResultBusca_Error");

            // busca por descrição do produto
            // ordena por data de cadastro desc            
            var modelBusca = produtoRepository.GetbyDescricao(descricao);

            ViewBag.NProdutos = modelBusca.Count();
            ViewBag.Tipo = 0;
            ViewBag.Console = 0;
            ViewBag.Descricao = descricao;
            ViewBag.Categoria = 0;
            ViewBag.Ordem = 2;        //DataLancamentoDESC  
            ViewBag.EhPesquisa = true;
            return View("ResultBusca", modelBusca);
        }

        public PartialViewResult BuscabyTipoConsoleDescricaoCategoriaOrdem(byte tipo, byte console, string descricao, byte categoria, int ordem)
        {
            // Exibe somente os produtos com o campo exibir=1
            // ordena por data de cadastro desc                        
            var modelBuscaOrd = produtoRepository.GetbyTipoConsoleDescricaoCategoriaOrdem(tipo, console, descricao, categoria, ordem );

            ViewBag.NProdutos = modelBuscaOrd.Count();
            ViewBag.Tipo = tipo;
            ViewBag.Console = console;            
            ViewBag.Descricao = descricao;
            ViewBag.Categoria = categoria;
            ViewBag.Ordem = ordem;
            
            return PartialView("ResultBusca_Detalhes", modelBuscaOrd);
        }


        public ActionResult Details(int idproduto)
        {
            var model = produtoRepository.GetbyID(idproduto);
            return View(model);
        }


    }
}

GameCatalogMVC/Views/Produto/DataList.cshtml
@using GameCatalogMVC.Models;
@model IEnumerable<Produto>

@{
    Layout = null;
}

<!DOCTYPE HTML>
<html lang="pt-br">
<head title="">
    <style type="text/css">    
        #divDataList
        {            
            margin: 0 auto;        
            font-family:Verdana;    
            font-size:small;        
            color:#4b4848; 
            padding-top: 30px;
            /*margin-left:9%;*/               
        }     
        .colunaProdutosEncontrados
        {     
            border-top: 1px solid #CFCFCF;        
            padding-top: 5px;                                        
            height:240px;
        }
        #imgthumbnail
        {
            /*width:168px;
            height:210px;*/                        
            width:134px;
            height:168px;
        } 
        .colunaSelecionada
        {
            border: 1px solid #CFCFCF;            
        }
        
    </style>
    
    <script type="text/javascript">
        $(document).ready(function () {
            $('.colunaProdutosEncontrados').hover(function () {
                $(this).addClass('colunaSelecionada');
            },
            function () {
                $(this).removeClass('colunaSelecionada');
            });
        });
     </script>
</head>

<body>       
    <div class="container-fluid">
        <div id="divDataList" class="container-fluid col-lg-12 col-md-12 col-sm-12 col-xs-12">
            @{                
                foreach (Produto p in Model)
                {                   
                    <div class='colunaProdutosEncontrados col-lg-2 col-md-3 col-sm-4 col-xs-12'>
                        <a href='@Url.Action("Details", "Produto", new {idproduto = @p.IdProduto })'>
                            <img id='imgthumbnail' src='@Url.Content("~/Content/fotos/" + @p.Foto)' alt='' />
                        </a>
                        <br />
                        @p.Descricao <br />
                        @if (!string.IsNullOrEmpty(p.Console.Descricao ))
                        {
                            @p.Console.Descricao <br />
                        }
                    </div>                  
                }                
            }                        
        </div>
    </div>
</body>
</html>

GameCatalogMVC/Views/Produto/Details.cshtml
@using GameCatalogMVC.Models;
@model Produto

@section Styles
{
    <style type="text/css">        
        #divdetails
        {             
            background-color: White;            
            height: auto;                        
            font-family: Verdana;  
            font-size: small;            
        }    
        #imgthumbnail
        {
            width:134px;
            height:168px;
        }
        .container-fluid {
            background-color: White;            
        }
    </style>        
}


    <div id="divdetails" class="container-fluid">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            @if (!string.IsNullOrWhiteSpace(@Model.Descricao ))
            {
                <span style="font-size: large; color:steelblue;">@Model.Descricao </span>
                <br />
            }

            <div style="margin-top:10px; margin-bottom:10px; width: 400px; border: 1px solid #BDBDBD">
                <br />
                <img id='imgthumbnail' src='@Url.Content("~/Content/fotos/" + @Model.Foto)' alt='' style="margin-left:110px;" />
                <br />
                <br />
            </div>
            @if (!string.IsNullOrEmpty(Model.Console.Descricao ))
            {
                <text>Console: </text>@Model.Console.Descricao <br />
            }
            @if (!string.IsNullOrWhiteSpace(@Model.Texto1))
            {
                @Model.Texto1<br />
            }
            @if (!string.IsNullOrWhiteSpace(@Model.Texto2))
            {
                @Model.Texto2<br />
            }
            @if (!string.IsNullOrWhiteSpace(@Model.Texto3))
            {
                @Model.Texto3<br />
            }
            @if (!string.IsNullOrWhiteSpace(@Model.Data_cadastro.ToString()))
            {
                <text>Data de Lançamento: </text> @Model.Data_cadastro.ToShortDateString()<br />
            }

            @if (!string.IsNullOrWhiteSpace(@Model.Site))
            {
                <a href='@Model.Site' target="_blank">Ver avaliação</a>
            }
            <br />
            <br />
            <br />
        </div>
    </div>

GameCatalogMVC/Views/Produto/ResultBusca.cshtml
@using GameCatalogMVC.Models;
@model IEnumerable<Produto>

@{
    ViewBag.Title = "ResultBusca";
}

@Html.Partial("ResultBusca_CabecalhoDetalhes")  

GameCatalogMVC/Views/Produto/ResultBusca_CabecalhoDetalhes.cshtml
@{    
    Layout = null;
}

<!DOCTYPE HTML>
<html lang="pt-br">
<head title="">    
    
    <style type="text/css"> 
        #divResultadoBusca
        {               
            background-color: White;
            color:#565656;                                
        }           
        #divResultadoBusca a, #divResultadoBusca a:hover
        {        
            color: Black;
            text-decoration:none;        
        }
        .Transparente
        {
            opacity:0.10;
	        -moz-opacity: 0.10;
	        filter: alpha(opacity=10);
        }                       
    </style>       

    <script type="text/javascript">

        $(document).ajaxStart(function () { 
            $('#divProdutosEncontrados').addClass('Transparente');
            $('#imgloader').css('display', 'block');

        });
        $(document).ajaxStop(function () { 
            $('#divProdutosEncontrados').removeClass('Transparente');
            $('#imgloader').css('display', 'none');
        });

            
        function BuscabyTipoConsoleDescricaoCategoriaOrdem() {
            
            var tipo = document.getElementById("hdnTipo").value;
            var console = document.getElementById("hdnConsole").value;
            var descricao = document.getElementById("hdnDescricao").value;
            var categoria = document.getElementById("hdnCategoria").value;
            var textoOrdem = document.getElementById("ddlOrdem").selectedIndex;            
            
            if (textoOrdem != null)
            {
                var link = '@Url.Action("BuscabyTipoConsoleDescricaoCategoriaOrdem", "Produto", new { tipo = "VV", console = "WW", descricao = "XX", categoria = "YY", ordem = "ZZ" })';
                var linkCategorias = '@Url.Action("ListaCategorias", "Categoria", new { tipo = "VV", console = "WW", ordem = "ZZ" })';
                if (tipo != null && tipo!= "0")
                {
                    link = link.replace("VV", tipo);
                    linkCategorias = linkCategorias.replace("VV", tipo);
                }
                else
                {
                    link = link.replace("VV", "0");
                    linkCategorias = link.replace("VV", "0");
                }

                if (console != null && console != "0") {
                    link = link.replace("WW", console);
                    linkCategorias = linkCategorias.replace("WW", console);
                }
                else
                {
                    link = link.replace("WW", "0");
                    linkCategorias = link.replace("WW", "0");
                }

                if (descricao != null && descricao != "0") {
                    link = link.replace("XX", descricao);
                }
                else
                {
                    link = link.replace("XX", "0");
                }

                if (categoria != null && categoria != "0") {
                    link = link.replace("YY", categoria);                    
                }
                else
                {
                    link = link.replace("YY", "0");
                }

                link = link.replace("ZZ", textoOrdem);
                linkCategorias = linkCategorias.replace("ZZ", textoOrdem);
            }

            $.ajax({
                url: link,
                type: 'get',
                beforeSend: function () {
                    $('#divProdutosEncontrados').addClass('Transparente');
                    $('#imgloader').css('display', 'block');                    
                },
                complete: function () {
                    $('#divProdutosEncontrados').removeClass('Transparente');
                    $('#imgloader').css('display', 'none');                    
                },
                success: function (data) {
                    $('#divProdutosEncontrados').html(data);
                },
                error: function () {
                    $('#divProdutosEncontrados').empty();
                }
            });
            
            if(descricao == "0") 
            {                
                $.ajax({
                    url: linkCategorias,
                    type: 'get',
                    beforeSend: function () { },
                    complete: function () {},
                    success: function (data) {
                        $('#divFiltroCategorias').html(data);
                    },
                    error: function () {
                        $('#divFiltroCategorias').empty();
                    }
                });
            }
        }    
    </script>     
</head>

<body>
    <div id="divResultadoBusca" class="container-fluid" style="padding-top:3%">        
            <br />
            <div id="divCabecalhoBusca" class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="padding-bottom:2%">
                @{
                    <div class="col-lg-10 col-md-9 col-sm-9 col-xs-12">
                        @if (@ViewBag.Mensagem != null)
                        {
                            <span style="font-size:large; color: #F37B20;">@ViewBag.Mensagem</span>
                        }
                        else
                        {
                            <span style="font-size:large ;color: #F37B20;">Resultado da busca por: <span style="color: #0082D6">@ViewBag.Descricao</span></span>
                        }
                        <br />
                        <span style="font-size:medium;">Produtos encontrados:&nbsp;<span id="numeroProdutosEncontrados" style="color: #0082D6;">@ViewBag.NProdutos</span></span>
                    </div>

                    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
                        <label for="ddlOrdem">Ordenar por:</label>
                        <select id="ddlOrdem" onchange="javascript: BuscabyTipoConsoleDescricaoCategoriaOrdem()">
                            <option value="NameASC">A - Z</option>
                            <option value="NameDESC">Z - A</option>
                            <option selected="selected" value="DataLancamentoDESC">Data de lançamento</option>
                        </select>
                    </div>
                }
                
            </div>
            @*na primeira chamada, guarda em um campo hidden o tipo de produto (1-console, 2-game, 3-acessório)*@
            <input type="hidden" id="hdnTipo" value="@ViewBag.Tipo" />
            @*na primeira chamada, guarda em um campo hidden o console (1-Playstation 3, 2-Playstation 2, 3-PSP, 4-xbox 360, 5-PC, 6-DS, 7-Wii)*@
            <input type="hidden" id="hdnConsole" value="@ViewBag.Console" />
            @*na primeira chamada, guarda em um campo hidden a descricao *@
            <input type="hidden" id="hdnDescricao" value="@ViewBag.Descricao" />
            @*na primeira chamada, guarda em um campo hidden a categoria *@
            <input type="hidden" id="hdnCategoria" value="@ViewBag.Categoria" />

            @if (@ViewBag.NProdutos != 0)
            {
                
                    <br />
                    <div>
                        @if (ViewBag.Tipo == 2)      // se for tipo game mostra o filtro de categorias à esquerda
                        {
                            @Html.Raw("<div id='divFiltroCategorias' class='col-lg-2 col-md-2 col-sm-3 col-xs-4'>")
                            @Html.Action("ListaCategorias", "Categoria", new { tipo = @ViewBag.Tipo, console = @ViewBag.Console, ordem = "2" })
                            @Html.Raw("</div> ")
                            // div container dos produtos (divs) à direita:
                            @Html.Raw("<div class='col-lg-10 col-md-10 col-sm-9 col-xs-8'>")
                        }
                        else
                        {
                            @Html.Raw("<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>")
                        }
                        <img alt='' id='imgloader' src='~/Content/images/loader.gif' style='display: none; position:absolute; top: 250px; left: 350px;' />
                        @Html.Raw("<div id='divProdutosEncontrados'")
                        @Html.Partial("ResultBusca_Detalhes")
                        @Html.Raw("</div>")
                        @Html.Raw("</div>")

                    </div>
            }
            else
            {
                <br />
            }        
    </div>
</body>
</html>

GameCatalogMVC/Views/Produto/ResultBusca_Detalhes.cshtml
@using GameCatalogMVC.Models;

@{    
    Layout = null;
}

<!DOCTYPE HTML>
<html lang="pt-br">
<head title="">
    <style type="text/css">   
        a span
        {   
            font-family:Verdana;    
            font-size:small;        
            color:#4b4848;             
        }         
        .colunaProdutosEncontrados
        {   
            border-top: 1px solid #CFCFCF;        
            padding-top: 10px;                
            padding-left:20px;
            padding-right:10px;
            padding-bottom:10px;    
            height:240px;                     
        }        
        .colunaSelecionada
        {
            border: 1px solid #CFCFCF;            
        }
        #imgthumbnailprodutosencontrados
        {
            width:134px;
            height:168px;
            border-style: none;
        }    
    </style>
    
    <script type="text/javascript">
        $(document).ready(function () {
            $('.colunaProdutosEncontrados').hover(function () {
                $(this).addClass('colunaSelecionada');
            },
            function () {
                $(this).removeClass('colunaSelecionada');
            });
            
        });
     </script>        
</head>

<body>          
    <input type="hidden" id="numeroProdutosEncontradosAux" value="@ViewBag.NProdutos" />    
    <input type="hidden" id="hdnCategoriaAux" value="@ViewBag.Categoria" />     
    <script type="text/javascript">
        document.getElementById("numeroProdutosEncontrados").innerHTML = document.getElementById("numeroProdutosEncontradosAux").value;
        document.getElementById("hdnCategoria").value = document.getElementById("hdnCategoriaAux").value;
    </script>
    
    @{  
            <div id="divDataListBuscaDetalhes">
                @foreach (Produto p in Model)
                {
                    if (ViewBag.EhPesquisa == true)      // se for feita a pesquisa, aumenta a quantidade de produtos (divs)
                    {
                        @Html.Raw("<div class='colunaProdutosEncontrados col-lg-2 col-md-3 col-sm-4 col-xs-12'>")
                    }
                    else
                    {
                        @Html.Raw("<div class='colunaProdutosEncontrados col-lg-3 col-md-3 col-sm-4 col-xs-12'>")
                    }

                    @* link sem ajax : *@
                    @* O link com ajax não foi feito porque o helper @Ajax.ActionLink não permite colocar imagens no link, só texto: *@
                    <a href='@Url.Action("Details", "Produto", new { idproduto = @p.IdProduto })'>
                        <img id='imgthumbnailprodutosencontrados' src='@Url.Content("~/Content/fotos/" + @p.Foto)' alt='' />
                        <br />
                        <span>@p.Descricao </span><br />
                        @if (!string.IsNullOrEmpty(p.Console.Descricao))
                        {
                            <span>@p.Console.Descricao </span>
                            <br />
                        }
                    </a>

                    @Html.Raw("</div>");
                }
            </div>
    }

</body>
</html>




GameCatalogMVC/Views/Produto/ResultBusca_Error.cshtml

@section Styles
{
    <style type="text/css">
        body
        {
            background-color: #F5F5F5;
        }    
        #divbusca_Error
        {            
            margin: 0 auto;  
            height: auto;  
            background-color: White;    
            font-family:Verdana;
            font-size: large;
            color:#565656;               
        }         
    </style>

}


    <div id="divbusca_Error">
        <br />
        Digite um texto para fazer a busca!
        <br />
        <br />
        <br />
    </div>
